version: '3.4'
name: ride23

services:
  gateway:
    container_name: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OpenIdOptions__Authority=http://identity:8080/
      - ReverseProxy__clusters__identity__destinations__identity__address=http://identity:8080
      - ReverseProxy__clusters__customer__destinations__customer__address=http://customer:8080
      - ReverseProxy__clusters__driver__destinations__driver__address=http://driver:8080
      - ReverseProxy__clusters__location__destinations__location__address=http://location:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456Aa!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Ride23.pfx
    ports:
      - 5002:8080
      - 7002:8081
    volumes:
      - ~/.aspnet/https:/https:ro
      - gateway-data:/app
    networks:
      - ride23

  customer:
    container_name: customer
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OpenIdOptions__Authority=http://identity:8080/
      - EFCoreOptions__ConnectionString=Host=postgres;Port=5430;Database=Ride23;Username=postgres;Password=admin;Include Error Detail=true
      - KafkaOptions__BootstrapServers=kafka:29092
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456Aa!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Ride23.pfx
    ports:
      - 5003:8080
      - 7003:8081
    volumes:
      - ~/.aspnet/https:/https:ro
      - customer-data:/app
    depends_on:
      - postgres
      - kafka
    networks:
      - ride23

  driver:
    container_name: driver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OpenIdOptions__Authority=http://identity:8080/
      - EFCoreOptions__ConnectionString=Host=postgres;Port=5430;Database=Ride23;Username=postgres;Password=admin;Include Error Detail=true
      - KafkaOptions__BootstrapServers=kafka:29092
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456Aa!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Ride23.pfx
    ports:
      - 5004:8080
      - 7004:8081
    volumes:
      - ~/.aspnet/https:/https:ro
      - driver-data:/app
    depends_on:
      - postgres
      - kafka
    networks:
      - ride23

  identity:
    container_name: identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5430;Database=Ride23;Username=postgres;Password=admin;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456Aa!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Ride23.pfx
    ports:
      - 5001:8080
      - 7001:8081
    volumes:
      - ~/.aspnet/https:/https:ro
      - identity-data:/app
    depends_on:
      - postgres
    networks:
      - ride23

  location:
    container_name: location
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OpenIdOptions__Authority=http://identity:8080/
      - KafkaOptions__BootstrapServers=kafka:29092
      - CachingOptions__RedisURL=redis:6379
      - CassandraOptions__ContactPoint=cassandra
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456Aa!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Ride23.pfx
    ports:
      - 5005:8080
      - 7005:8081
    volumes:
      - ~/.aspnet/https:/https:ro
      - location-data:/app
    depends_on:
      - cassandra
      - kafka
    networks:
      - ride23

volumes:
  gateway-data:
  customer-data:
  driver-data:
  identity-data:
  location-data:

networks:
  ride23:
    name: ride23
